Repository openrewrite/rewrite-templating, pull requests merged in 2025-04, with the labels that each got.

#131 Fix compiler error on JDK9+
  src/main/java/org/openrewrite/java/template/internal/JavacResolution.java
Labels: bug

#135 add license information to MANIFEST.MF
  build.gradle.kts
Labels: documentation, enhancement

#134 Generics
  src/main/java/org/openrewrite/java/template/internal/TemplateCode.java
  src/main/java/org/openrewrite/java/template/processor/RefasterTemplateProcessor.java
  src/main/java/org/openrewrite/java/template/processor/TemplateProcessor.java
  src/test/java/org/openrewrite/java/template/RefasterTemplateProcessorTest.java
  src/test/resources/refaster/ComplexGenerics.java
  src/test/resources/refaster/ComplexGenericsRecipe.java
  src/test/resources/refaster/Generics.java
  src/test/resources/refaster/GenericsRecipes.java
  src/test/resources/refaster/InvalidRecipe.java
  src/test/resources/refaster/MultimapGet.java
  src/test/resources/refaster/MultimapGetRecipe.java
  src/test/resources/refaster/OrElseGetGetRecipe.java
  src/test/resources/refaster/PicnicRulesRecipes.java
  src/test/resources/refaster/PreconditionsVerifierRecipes.java
Labels: enhancement

#137 Add RSPEC tags to generated recipes from suppressed class warnings
  src/main/java/org/openrewrite/java/template/processor/RefasterTemplateProcessor.java
  src/test/java/org/openrewrite/java/template/RefasterTemplateProcessorTest.java
  src/test/resources/refaster/SuppressedWarningsAsTags.java
  src/test/resources/refaster/SuppressedWarningsAsTagsRecipes.java
Labels: documentation, enhancement
